services:
  - type: web
    name: rescue-ml-api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y git-lfs
      git lfs pull
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true